// data.js — loads the public GeoJSON layers and derives a small in-memory
// spatial index used by search, analytics and the info drawer. All data
// originates from data/diriyah/*.geojson, generated by
// scripts/convert-map-data.mjs and scripts/generate-poi.mjs from real OSM
// footprints (see README for provenance).

const BASE = new URL('../../data/diriyah/', import.meta.url);

async function loadGeojson(name) {
  const res = await fetch(new URL(`${name}.geojson`, BASE));
  if (!res.ok) throw new Error(`Failed to load ${name}.geojson: ${res.status}`);
  return res.json();
}

export async function loadAllLayers() {
  const names = ['buildings', 'roads', 'water', 'green', 'landmarks', 'poi', 'boundary'];
  const results = await Promise.all(names.map(loadGeojson));
  return Object.fromEntries(names.map((n, i) => [n, results[i]]));
}

// Every named, searchable/clickable point feature in one flat list.
export function buildSearchIndex(layers) {
  const items = [];
  for (const f of layers.landmarks.features) {
    items.push({
      id: f.properties.id,
      name_en: f.properties.name_en,
      name_ar: f.properties.name_ar,
      category: 'heritage',
      icon: f.properties.icon,
      coordinates: f.geometry.coordinates,
      properties: f.properties,
    });
  }
  for (const f of layers.poi.features) {
    items.push({
      id: f.properties.id,
      name_en: f.properties.name_en,
      name_ar: f.properties.name_ar,
      category: f.properties.category,
      icon: f.properties.category === 'hospitality' ? '\u{1F3E8}' : '\u{1F6CD}️',
      coordinates: f.geometry.coordinates,
      properties: f.properties,
    });
  }
  return items;
}

export function searchFeatures(index, query, lang) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const key = lang === 'ar' ? 'name_ar' : 'name_en';
  return index
    .filter((it) => (it[key] || '').toLowerCase().includes(q) || (it.name_en || '').toLowerCase().includes(q))
    .slice(0, 12);
}

// Centroid of the study-area boundary, used to initialise the map camera.
export function studyAreaCenter(boundaryFc) {
  const ring = boundaryFc.features[0].geometry.coordinates[0];
  let x = 0;
  let y = 0;
  for (const [lon, lat] of ring) {
    x += lon;
    y += lat;
  }
  return [x / ring.length, y / ring.length];
}
